use super::KubeVirtCloudConfig;
use crate::network::DhcpSetting;
use crate::providers::MetadataProvider;

use ipnetwork::IpNetwork;
use pnet_base::MacAddr;
use std::net::IpAddr;
use std::path::Path;
use std::str::FromStr;

#[test]
fn test_kubevirt_parse_full_metadata_json() {
    let fixture = Path::new("./tests/fixtures/kubevirt/full_metadata");
    let config = KubeVirtCloudConfig::try_new(fixture).expect("cannot parse config");
    let attrs = config.attributes().expect("cannot get attributes");
    assert_eq!(attrs.len(), 3);
    assert_eq!(
        attrs.get("KUBEVIRT_INSTANCE_ID"),
        Some(&"5d307ca9-b3ef-428c-8861-06e72d69f223".to_string())
    );
    assert_eq!(
        attrs.get("KUBEVIRT_HOSTNAME"),
        Some(&"test_instance-kubevirt.foo.cloud".to_string())
    );
    assert_eq!(
        attrs.get("KUBEVIRT_INSTANCE_TYPE"),
        Some(&"some_type".to_string())
    );
    let obtained_ssh_keys = config.ssh_keys().expect("cannot extract public ssh keys");
    let expect_ssh_keys = openssh_keys::PublicKey::parse("ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAAgQDYVEprvtYJXVOBN0XNKVVRNCRX6BlnNbI+USLGais1sUWPwtSg7z9K9vhbYAPUZcq8c/s5S9dg5vTHbsiyPCIDOKyeHba4MUJq8Oh5b2i71/3BISpyxTBH/uZDHdslW2a+SrPDCeuMMoss9NFhBdKtDkdG9zyi0ibmCP6yMdEX8Q== Generated by Nova").expect("cannot parse expected ssh key");
    assert_eq!(obtained_ssh_keys.len(), 1);
    assert_eq!(obtained_ssh_keys[0], expect_ssh_keys);
}

#[test]
fn test_network_data() {
    let versions = ["v1", "v2"];
    let formats = ["json", "yaml"];
    for version in &versions {
        for format in &formats {
            let fixture_path = format!(
                "./tests/fixtures/kubevirt/network_data_{}_{}",
                version, format
            );
            let fixture = Path::new(fixture_path.as_str());
            let config = KubeVirtCloudConfig::try_new(fixture).expect(&fixture_path);
            let interfaces = config.networks().expect(&fixture_path);

            assert_eq!(interfaces.len(), 2, "{}", fixture_path);
            let (eth0_idx, eth1_idx) = if interfaces[0].name == Some("eth0".to_string()) {
                (0, 1)
            } else {
                (1, 0)
            };
            assert_eq!(
                interfaces[eth0_idx].name,
                Some("eth0".to_string()),
                "{}",
                fixture_path
            );
            assert_eq!(
                interfaces[eth0_idx].ip_addresses.len(),
                2,
                "{}",
                fixture_path
            );
            assert!(
                interfaces[eth0_idx]
                    .ip_addresses
                    .contains(&IpNetwork::from_str("192.168.1.10/24").unwrap()),
                "{}",
                fixture_path
            );
            assert!(
                interfaces[eth0_idx]
                    .ip_addresses
                    .contains(&IpNetwork::from_str("2001:db8::10/64").unwrap()),
                "{}",
                fixture_path
            );
            assert_eq!(interfaces[eth0_idx].routes.len(), 2, "{}", fixture_path);
            assert!(
                interfaces[eth0_idx]
                    .routes
                    .iter()
                    .any(|r| r.gateway == IpAddr::from_str("192.168.1.1").unwrap()),
                "{}",
                fixture_path
            );
            assert!(
                interfaces[eth0_idx]
                    .routes
                    .iter()
                    .any(|r| r.gateway == IpAddr::from_str("2001:db8::1").unwrap()),
                "{}",
                fixture_path
            );
            assert_eq!(
                interfaces[eth0_idx].nameservers.len(),
                4,
                "{}",
                fixture_path
            );
            assert!(
                interfaces[eth0_idx]
                    .nameservers
                    .contains(&IpAddr::from_str("8.8.8.8").unwrap()),
                "{}",
                fixture_path
            );
            assert!(
                interfaces[eth0_idx]
                    .nameservers
                    .contains(&IpAddr::from_str("8.8.4.4").unwrap()),
                "{}",
                fixture_path
            );
            assert!(
                interfaces[eth0_idx]
                    .nameservers
                    .contains(&IpAddr::from_str("2001:4860:4860::8888").unwrap()),
                "{}",
                fixture_path
            );
            assert!(
                interfaces[eth0_idx]
                    .nameservers
                    .contains(&IpAddr::from_str("2001:4860:4860::8844").unwrap()),
                "{}",
                fixture_path
            );
            assert_eq!(
                interfaces[eth1_idx].name,
                Some("eth1".to_string()),
                "{}",
                fixture_path
            );
            assert_eq!(
                interfaces[eth1_idx].dhcp,
                Some(DhcpSetting::Both),
                "{}",
                fixture_path
            );
            assert_eq!(
                interfaces[eth1_idx].ip_addresses.len(),
                0,
                "{}",
                fixture_path
            );
            assert_eq!(
                interfaces[eth1_idx].nameservers.len(),
                0,
                "{}",
                fixture_path
            );
            let kargs = config.rd_network_kargs().unwrap().unwrap();
            let kargs_parts: Vec<&str> = kargs.split_whitespace().collect();
            assert_eq!(kargs_parts.len(), 4, "{}", fixture_path);
            assert!(kargs.contains("ip=eth1:dhcp,dhcp6"), "{}", fixture_path);
            assert!(
                kargs.contains("ip=192.168.1.10::192.168.1.1:255.255.255.0::eth0:static"),
                "{}",
                fixture_path
            );
            assert!(
                kargs.contains("ip=2001:db8::10::2001:db8::1:64::eth0:static"),
                "{}",
                fixture_path
            );
            assert!(
                kargs.contains(
                    "nameserver=8.8.8.8,8.8.4.4,2001:4860:4860::8888,2001:4860:4860::8844"
                ),
                "{}",
                fixture_path
            );
            let attrs = config.attributes().expect(&fixture_path);
            assert_eq!(
                attrs.get("KUBEVIRT_IPV4"),
                Some(&"192.168.1.10".to_string()),
                "{}",
                fixture_path
            );
            assert_eq!(
                attrs.get("KUBEVIRT_IPV6"),
                Some(&"2001:db8::10".to_string()),
                "{}",
                fixture_path
            );
        }
    }
}
